# Django 基础设置
DEBUG = true
SECRET_KEY = "django-insecure-9=mmh+@=6*b@)6xhdxd7h&z4-v+=%5k4xjh1ua!84%qa=p8iwo"

# Sentry配置
SENTRY_DSN = "https://b16efab7c63449cdebeac330987c2756@o509082.ingest.us.sentry.io/4509551281373184"
SENTRY_ENVIRONMENT = "development"

# Neon PostgreSQL 数据库配置(developer数据库)
[database.dev] # dev 环境
DB_NAME = "booking_db"
DB_USER = "booking_dev"
DB_PASSWORD = "npg_a7YbiG4ltvZg"
DB_HOST = "ep-patient-sea-a1iw5n34-pooler.ap-southeast-1.aws.neon.tech"
DB_PORT = 5432
DB_SSLMODE = "require"


# Redis 基础设置(用于区分本地与服务器的redis连接)
[redis.test] # 测试 环境
REDIS_HOST = "81.68.79.234"
REDIS_PORT = 6379
REDIS_DB = 0
REDIS_PASSWORD = "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"