# Generated by Django 6.0.3 on 2026-03-31 13:31

import apps.inquiries.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('full_name', models.CharField(max_length=120, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='公司')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='电话')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='国家')),
                ('business_type', models.CharField(blank=True, max_length=120, verbose_name='业务类型')),
                ('target_use_case', models.CharField(blank=True, max_length=160, verbose_name='目标场景')),
                ('message', models.TextField(verbose_name='留言')),
                ('status', models.PositiveSmallIntegerField(choices=apps.inquiries.models.InquiryStatus.choices, db_index=True, default=apps.inquiries.models.InquiryStatus['NEW'], help_text='询盘流转状态。', verbose_name='询盘状态')),
                ('consent_to_contact', models.BooleanField(default=True, verbose_name='同意联系')),
            ],
            options={
                'verbose_name': '询盘',
                'verbose_name_plural': '询盘',
                'db_table': 'inquiry',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InquirySourceContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('source_page_type', models.CharField(blank=True, max_length=80, verbose_name='来源页面类型')),
                ('source_page_path', models.CharField(blank=True, max_length=255, verbose_name='来源页面路径')),
                ('source_page_title', models.CharField(blank=True, max_length=255, verbose_name='来源页面标题')),
                ('utm_source', models.CharField(blank=True, max_length=120, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, max_length=120, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='UTM Campaign')),
                ('referer', models.URLField(blank=True, verbose_name='Referer')),
                ('inquiry', models.OneToOneField(help_text='所属询盘。', on_delete=django.db.models.deletion.CASCADE, related_name='source_context', to='inquiries.inquiry', verbose_name='询盘')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, help_text='来源产品，可为空以保留历史询盘。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_contexts', to='catalog.product', verbose_name='产品')),
                ('variant', models.ForeignKey(blank=True, db_constraint=False, help_text='来源产品变体，可为空以保留历史询盘。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiry_contexts', to='catalog.productvariant', verbose_name='产品变体')),
            ],
            options={
                'verbose_name': '询盘来源上下文',
                'verbose_name_plural': '询盘来源上下文',
                'db_table': 'inquiry_source_context',
            },
        ),
    ]
