# Generated by Django 6.0.3 on 2026-03-31 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebuyerpath',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='买家路径卡片背景图。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_path_assets', to='core.mediaasset', verbose_name='背景图'),
        ),
        migrations.AddField(
            model_name='homeconfig',
            name='hero_image',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='首页 Hero 区背景图。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_hero_images', to='core.mediaasset', verbose_name='Hero 背景图'),
        ),
        migrations.AddField(
            model_name='homeconfig',
            name='value_section_image',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='首页价值点区右侧配图。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_value_images', to='core.mediaasset', verbose_name='价值区配图'),
        ),
        migrations.AddField(
            model_name='homebuyerpath',
            name='home',
            field=models.ForeignKey(db_constraint=False, help_text='所属首页配置。', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_paths', to='content.homeconfig', verbose_name='首页配置'),
        ),
        migrations.AddField(
            model_name='homefeaturedcard',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='卡片配图。允许资源替换或删除后保留卡片记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_feature_cards', to='core.mediaasset', verbose_name='媒体资源'),
        ),
        migrations.AddField(
            model_name='homefeaturedcard',
            name='home',
            field=models.ForeignKey(db_constraint=False, help_text='所属首页配置。', on_delete=django.db.models.deletion.CASCADE, related_name='featured_cards', to='content.homeconfig', verbose_name='首页配置'),
        ),
        migrations.AddField(
            model_name='homeproofitem',
            name='asset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='证明内容配图。允许资源替换或删除后保留证明项记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_proof_items', to='core.mediaasset', verbose_name='媒体资源'),
        ),
        migrations.AddField(
            model_name='homeproofitem',
            name='home',
            field=models.ForeignKey(db_constraint=False, help_text='所属首页配置。', on_delete=django.db.models.deletion.CASCADE, related_name='proof_items', to='content.homeconfig', verbose_name='首页配置'),
        ),
        migrations.AddConstraint(
            model_name='resourcearticle',
            constraint=models.UniqueConstraint(fields=('slug',), name='uniq_resource_article_slug'),
        ),
        migrations.AddConstraint(
            model_name='resourcearticle',
            constraint=models.UniqueConstraint(fields=('url_path',), name='uniq_resource_article_path'),
        ),
        migrations.AddConstraint(
            model_name='solutionpage',
            constraint=models.UniqueConstraint(fields=('slug',), name='uniq_solution_page_slug'),
        ),
        migrations.AddConstraint(
            model_name='solutionpage',
            constraint=models.UniqueConstraint(fields=('url_path',), name='uniq_solution_page_path'),
        ),
        migrations.AddConstraint(
            model_name='homeconfig',
            constraint=models.UniqueConstraint(fields=('slug',), name='uniq_home_config_slug'),
        ),
        migrations.AddConstraint(
            model_name='homeconfig',
            constraint=models.UniqueConstraint(fields=('url_path',), name='uniq_home_config_path'),
        ),
    ]
