# Generated by Django 6.0.3 on 2026-04-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypage',
            name='lead_text',
            field=models.TextField(blank=True, help_text='用于页面 Hero 标题下的首段导语。应先说明内容适合谁、解决什么问题；不要与摘要重复。', verbose_name='导语'),
        ),
        migrations.AlterField(
            model_name='companypage',
            name='primary_query',
            field=models.CharField(blank=True, help_text='SEO/GEO 用的核心目标查询词，不在前台直接展示，用于校准 H1、title、meta 与正文主题。', max_length=160, verbose_name='主查询词'),
        ),
        migrations.AlterField(
            model_name='companypage',
            name='secondary_queries',
            field=models.TextField(blank=True, help_text='SEO/GEO 用的次级查询词，每行一个；不在前台直接展示，用于 FAQ、内链、相关资源与内容覆盖规划。', verbose_name='次级查询词'),
        ),
        migrations.AlterField(
            model_name='homeconfig',
            name='lead_text',
            field=models.TextField(blank=True, help_text='用于页面 Hero 标题下的首段导语。应先说明内容适合谁、解决什么问题；不要与摘要重复。', verbose_name='导语'),
        ),
        migrations.AlterField(
            model_name='homeconfig',
            name='primary_query',
            field=models.CharField(blank=True, help_text='SEO/GEO 用的核心目标查询词，不在前台直接展示，用于校准 H1、title、meta 与正文主题。', max_length=160, verbose_name='主查询词'),
        ),
        migrations.AlterField(
            model_name='homeconfig',
            name='secondary_queries',
            field=models.TextField(blank=True, help_text='SEO/GEO 用的次级查询词，每行一个；不在前台直接展示，用于 FAQ、内链、相关资源与内容覆盖规划。', verbose_name='次级查询词'),
        ),
        migrations.AlterField(
            model_name='resourcearticle',
            name='lead_text',
            field=models.TextField(blank=True, help_text='用于页面 Hero 标题下的首段导语。应先说明内容适合谁、解决什么问题；不要与摘要重复。', verbose_name='导语'),
        ),
        migrations.AlterField(
            model_name='resourcearticle',
            name='primary_query',
            field=models.CharField(blank=True, help_text='SEO/GEO 用的核心目标查询词，不在前台直接展示，用于校准 H1、title、meta 与正文主题。', max_length=160, verbose_name='主查询词'),
        ),
        migrations.AlterField(
            model_name='resourcearticle',
            name='secondary_queries',
            field=models.TextField(blank=True, help_text='SEO/GEO 用的次级查询词，每行一个；不在前台直接展示，用于 FAQ、内链、相关资源与内容覆盖规划。', verbose_name='次级查询词'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='lead_text',
            field=models.TextField(blank=True, help_text='用于页面 Hero 标题下的首段导语。应先说明内容适合谁、解决什么问题；不要与摘要重复。', verbose_name='导语'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='primary_query',
            field=models.CharField(blank=True, help_text='SEO/GEO 用的核心目标查询词，不在前台直接展示，用于校准 H1、title、meta 与正文主题。', max_length=160, verbose_name='主查询词'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='secondary_queries',
            field=models.TextField(blank=True, help_text='SEO/GEO 用的次级查询词，每行一个；不在前台直接展示，用于 FAQ、内链、相关资源与内容覆盖规划。', verbose_name='次级查询词'),
        ),
    ]
