# Generated by Django 6.0.3 on 2026-03-31 13:31

import apps.core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLinkGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('title', models.CharField(max_length=120, verbose_name='分组标题')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='分组说明')),
            ],
            options={
                'verbose_name': '页脚链接组',
                'verbose_name_plural': '页脚链接组',
                'db_table': 'footer_link_group',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='资源标题')),
                ('asset_kind', models.PositiveSmallIntegerField(choices=apps.core.models.AssetKind.choices, db_index=True, default=apps.core.models.AssetKind['IMAGE'], help_text='结构化媒体类型。', verbose_name='资源类型')),
                ('file_url', models.URLField(verbose_name='资源地址')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Alt 文本')),
                ('mime_type', models.CharField(blank=True, max_length=120, verbose_name='MIME 类型')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='宽度')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='高度')),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='文件大小')),
            ],
            options={
                'verbose_name': '媒体资源',
                'verbose_name_plural': '媒体资源',
                'db_table': 'media_asset',
                'ordering': ('title', 'id'),
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名')),
                ('brand_name', models.CharField(max_length=255, verbose_name='品牌名')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='法定名称')),
                ('short_description', models.TextField(blank=True, verbose_name='简介')),
                ('headquarters_city', models.CharField(blank=True, max_length=120, verbose_name='城市')),
                ('headquarters_region', models.CharField(blank=True, max_length=120, verbose_name='地区')),
                ('country', models.CharField(default='China', max_length=120, verbose_name='国家')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='成立年份')),
                ('primary_email', models.EmailField(blank=True, max_length=254, verbose_name='主邮箱')),
                ('primary_phone', models.CharField(blank=True, max_length=80, verbose_name='主电话')),
                ('website_url', models.URLField(blank=True, verbose_name='官网')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='地址')),
                ('postal_code', models.CharField(blank=True, max_length=32, verbose_name='邮编')),
            ],
            options={
                'verbose_name': '组织资料',
                'verbose_name_plural': '组织资料',
                'db_table': 'organization_profile',
                'ordering': ('company_name',),
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('label', models.CharField(max_length=120, verbose_name='链接名称')),
                ('url_path', models.CharField(max_length=255, verbose_name='路径')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='新窗口打开')),
                ('group', models.ForeignKey(db_constraint=False, help_text='所属页脚链接组。', on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footerlinkgroup', verbose_name='链接组')),
            ],
            options={
                'verbose_name': '页脚链接',
                'verbose_name_plural': '页脚链接',
                'db_table': 'footer_link',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('label', models.CharField(max_length=120, verbose_name='名称')),
                ('url_path', models.CharField(max_length=255, verbose_name='路径')),
                ('location', models.PositiveSmallIntegerField(choices=apps.core.models.NavigationLocation.choices, db_index=True, default=apps.core.models.NavigationLocation['PRIMARY'], help_text='导航所在区域。', verbose_name='导航位置')),
                ('open_in_new_tab', models.BooleanField(default=False, verbose_name='新窗口打开')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='为空时表示顶级导航。', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navigationitem', verbose_name='父导航')),
            ],
            options={
                'verbose_name': '导航项',
                'verbose_name_plural': '导航项',
                'db_table': 'navigation_item',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('channel_type', models.PositiveSmallIntegerField(choices=apps.core.models.ContactChannelType.choices, db_index=True, default=apps.core.models.ContactChannelType['EMAIL'], help_text='联系方式类型。', verbose_name='联系方式类型')),
                ('placement', models.PositiveSmallIntegerField(choices=apps.core.models.ContactPlacement.choices, db_index=True, default=apps.core.models.ContactPlacement['GLOBAL'], help_text='该联系方式主要出现的位置。', verbose_name='展示位置')),
                ('label', models.CharField(max_length=120, verbose_name='标签')),
                ('value', models.CharField(max_length=255, verbose_name='值')),
                ('href', models.CharField(blank=True, max_length=255, verbose_name='链接')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主要联系方式')),
                ('organization', models.ForeignKey(db_constraint=False, help_text='联系方式所属组织。', on_delete=django.db.models.deletion.CASCADE, related_name='contact_channels', to='core.organizationprofile', verbose_name='组织')),
            ],
            options={
                'verbose_name': '联系方式',
                'verbose_name_plural': '联系方式',
                'db_table': 'contact_channel',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PageRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('source_object_id', models.PositiveBigIntegerField(verbose_name='源对象 ID')),
                ('target_object_id', models.PositiveBigIntegerField(verbose_name='目标对象 ID')),
                ('relation_type', models.PositiveSmallIntegerField(choices=apps.core.models.PageRelationType.choices, default=apps.core.models.PageRelationType['RELATED'], help_text='页面之间的结构化关系。', verbose_name='关系类型')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('source_content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='page_relation_sources', to='contenttypes.contenttype', verbose_name='源内容类型')),
                ('target_content_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='page_relation_targets', to='contenttypes.contenttype', verbose_name='目标内容类型')),
            ],
            options={
                'verbose_name': '页面关系',
                'verbose_name_plural': '页面关系',
                'db_table': 'page_relation',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('source_content_type', 'source_object_id', 'target_content_type', 'target_object_id', 'relation_type'), name='uniq_page_relation_edge')],
            },
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='对象 ID')),
                ('schema_profile', models.CharField(blank=True, max_length=80, verbose_name='Schema Profile')),
                ('og_title', models.CharField(blank=True, max_length=255, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=320, verbose_name='OG Description')),
                ('twitter_title', models.CharField(blank=True, max_length=255, verbose_name='Twitter Title')),
                ('twitter_description', models.CharField(blank=True, max_length=320, verbose_name='Twitter Description')),
                ('robots_directives', models.CharField(blank=True, max_length=255, verbose_name='Robots 指令')),
                ('content_type', models.ForeignKey(db_constraint=False, help_text='SEO 扩展绑定的内容类型。', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('og_image', models.ForeignKey(blank=True, db_constraint=False, help_text='社交分享图。允许图片资源替换或删除后保留 SEO 配置。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_og_references', to='core.mediaasset', verbose_name='OG 图片')),
            ],
            options={
                'verbose_name': '页面 SEO',
                'verbose_name_plural': '页面 SEO',
                'db_table': 'page_seo',
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='uniq_page_seo_target')],
            },
        ),
    ]
