"""
Django settings for booking project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import sys
import tomllib

from pathlib import Path
from django.utils import timezone

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
CONFIG_FILE = BASE_DIR / "config.toml"
with open(CONFIG_FILE, "rb") as f:
    config = tomllib.load(f)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config['SECRET_KEY']

DEBUG = config["DEBUG"]

# 从环境变量读取ALLOWED_HOSTS，如果没有则使用默认值
ALLOWED_HOSTS = config.get('ALLOWED_HOSTS', '').split(',') if config.get('ALLOWED_HOSTS') else [
    'www.protaylor.com',   # ← 生产域名（替换 mengdie.ai）
    'protaylor.com',
    'api.protaylor.com',   # ← 如果 API 单独子域

    # 本地开发
    'localhost',
    '127.0.0.1',
    '0.0.0.0',

    # 服务器IP
    '47.237.84.36',
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "apps.core",
    "apps.catalog",
    "apps.content",
    "apps.inquiries",
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # 启用CORS中间件
    'utils.middleware.ConditionalSessionMiddleware',  # 条件性Session，仅Admin使用
    'django.middleware.common.CommonMiddleware',
    'utils.csrf_middleware.ApiCsrfExemptMiddleware',  # API CSRF豁免
    'utils.csrf_middleware.SmartCsrfViewMiddleware',  # 智能CSRF保护（admin等需要）
    'utils.middleware.ConditionalAuthMiddleware',  # 条件性认证，仅Admin使用
    'utils.middleware.ConditionalMessageMiddleware',  # 条件性消息，仅Admin使用
    # 'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = "protaylor_api.urls"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = "protaylor_api.wsgi.application"
ASGI_APPLICATION = "protaylor_api.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 检查是否在运行测试
TESTING = 'test' in sys.argv or 'pytest' in sys.modules or any('test' in arg for arg in sys.argv)

REDIS_CONFIG = {
    'host': 'redis',
    'password': '',
    'port': 6379,
    'db': 0,
    'decode_responses': True,
    'socket_connect_timeout': 5,
    'socket_timeout': 5,
}

if TESTING:
    # 测试环境：使用测试服务器Redis配置
    print("🧪 测试模式：使用测试服务器Redis配置")
    REDIS_CONFIG = {
        'host': config["redis"]["test"].get('REDIS_HOST', 'redis'),
        'password': config["redis"]["test"].get('REDIS_PASSWORD', ''),
        'port': config["redis"]["test"].get('REDIS_PORT', 6379),
        'db': config["redis"]["test"].get('REDIS_DB', 0),
        'decode_responses': True,
        'socket_connect_timeout': 5,
        'socket_timeout': 5,
    }
    redis_url = f"redis://:{REDIS_CONFIG['password']}@{REDIS_CONFIG['host']}:{REDIS_CONFIG['port']}/{REDIS_CONFIG['db']}"
else:
    if REDIS_CONFIG['password']:
        redis_url = f"redis://:{REDIS_CONFIG['password']}@{REDIS_CONFIG['host']}:{REDIS_CONFIG['port']}/{REDIS_CONFIG['db']}"
    else:
        redis_url = f"redis://{REDIS_CONFIG['host']}:{REDIS_CONFIG['port']}/{REDIS_CONFIG['db']}"

if TESTING:
    # 测试环境：默认使用PostgreSQL测试数据库（与生产环境一致）
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'foreign_trade_test',
            'USER': 'postgres',
            'PASSWORD': '123456',
            'HOST': '127.0.0.1',
            'PORT': '5432',
            'OPTIONS': {
                'sslmode': 'disable',  # 测试环境不需要SSL
            },
            'TEST': {
                'NAME': config.get('UNIT_TESTING_DB_NAME', f'unit_testing_{timezone.now().strftime("%Y%m%d_%H%M%S")}'),
                'DEPENDENCIES': [],  # 避免旧连接
                'SERIALIZE': True,   # 启用序列化，确保测试隔离
            },
        }
    }
    print("🐘 测试模式：使用PostgreSQL测试数据库")
else:
    # 开发和生产环境：使用Neon PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config['database']['dev'].get('DB_NAME'),
            'USER': config['database']['dev'].get('DB_USER'),
            'PASSWORD': config['database']['dev'].get('DB_PASSWORD'),
            'HOST': config['database']['dev'].get('DB_HOST'),
            'PORT': config['database']['dev'].get('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': config['database']['dev'].get('DB_SSLMODE', 'require'),  # Neon数据库需要SSL
                # 关键设置
                "channel_binding": "require",  # Neon数据库需要
            },
            'CONN_MAX_AGE': 60,  # 连接复用, 连接保持60秒
            # 启用连接健康检查(启用CONN_HEALTH_CHECKS,Django会自动检测连接是否已断开,避免connection failed)
            'CONN_HEALTH_CHECKS': False,  # 不能使用，否则Neon PG的compute一直计费
        }
    }
    if DEBUG:
        print("🐘 开发模式：使用Neon PostgreSQL数据库")
    else:
        print("🚀 生产模式：使用Neon PostgreSQL数据库")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_DIRS[0].mkdir(parents=True, exist_ok=True)     # 若 static 目录不存在则自动创建

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS设置
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://47.237.84.36",

    # 开发环境
    "http://localhost:3000",  # Next.js dev server
    "http://127.0.0.1:3000",

    # 生产环境
    "https://www.protaylor.com",  # ← 替换为真实域名
    "https://protaylor.com",
]

CORS_ALLOW_CREDENTIALS = True

# CSRF设置 - 前后端分离友好配置
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://47.237.84.36",
    "https://protaylor.com",
]

# API接口CSRF豁免URL模式
CSRF_EXEMPT_URLS = [
    r'^api/',  # 所有以api/开头的路径
    r'^admin/',  # admin后台也豁免（临时解决方案）
    r'^static/',   # 静态文件豁免CSRF检查
    r'^media/',    # 媒体文件豁免CSRF检查
]

# CSRF Cookie设置 - 适配HTTPS和前后端分离
CSRF_COOKIE_SECURE = False  # 仅在HTTPS下传输
CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript访问（前端可能需要）
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_USE_SESSIONS = False  # 使用cookie而不是session存储CSRF token


# 代理相关设置 - 适配Caddy反向代理
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# 会话设置 - 仅Admin使用
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# 日志设置
LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(parents=True, exist_ok=True)     # 若 logs 目录不存在则自动创建

DJANGO_LOG_FILE = LOG_DIR / "django.log"
DJANGO_LOG_FILE.touch(exist_ok=True)           # 保证日志文件存在（不会覆盖已有内容）

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': str(DJANGO_LOG_FILE),
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
