# Generated by Django 6.0.3 on 2026-03-31 13:31

import apps.catalog.models
import common.enums
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('title', models.CharField(max_length=160, verbose_name='下载标题')),
                ('download_kind', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductDownloadKind.choices, default=apps.catalog.models.ProductDownloadKind['OTHER'], help_text='下载文件类型。', verbose_name='下载类型')),
            ],
            options={
                'verbose_name': '产品下载',
                'verbose_name_plural': '产品下载',
                'db_table': 'product_download',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('title', models.CharField(max_length=160, verbose_name='卖点标题')),
                ('body', models.TextField(verbose_name='卖点说明')),
            ],
            options={
                'verbose_name': '产品卖点',
                'verbose_name_plural': '产品卖点',
                'db_table': 'product_feature',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('media_kind', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductMediaKind.choices, default=apps.catalog.models.ProductMediaKind['GALLERY'], help_text='媒体展示类型。', verbose_name='媒体类型')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否主图')),
                ('alt_override', models.CharField(blank=True, max_length=255, verbose_name='Alt 覆盖')),
            ],
            options={
                'verbose_name': '产品媒体',
                'verbose_name_plural': '产品媒体',
                'db_table': 'product_media',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('relation_type', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductRelationType.choices, default=apps.catalog.models.ProductRelationType['RELATED_PRODUCT'], help_text='相关推荐还是相关资源。', verbose_name='关系类型')),
            ],
            options={
                'verbose_name': '产品关系',
                'verbose_name_plural': '产品关系',
                'db_table': 'product_relation',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('title', models.CharField(max_length=160, verbose_name='分组标题')),
                ('group_kind', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductSpecGroupKind.choices, default=apps.catalog.models.ProductSpecGroupKind['TECHNICAL'], help_text='规格组类型。', verbose_name='分组类型')),
            ],
            options={
                'verbose_name': '规格分组',
                'verbose_name_plural': '规格分组',
                'db_table': 'product_spec_group',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSpecRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('label', models.CharField(max_length=160, verbose_name='规格名称')),
                ('value', models.CharField(max_length=255, verbose_name='规格值')),
                ('unit', models.CharField(blank=True, max_length=40, verbose_name='单位')),
                ('is_highlight', models.BooleanField(db_index=True, default=False, verbose_name='是否高亮')),
            ],
            options={
                'verbose_name': '规格行',
                'verbose_name_plural': '规格行',
                'db_table': 'product_spec_row',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductUseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('icon', models.CharField(blank=True, help_text='Material Icon slug，如 restaurant / hotel / icecream。', max_length=60, verbose_name='图标')),
                ('title', models.CharField(max_length=160, verbose_name='场景标题')),
                ('summary', models.TextField(verbose_name='场景说明')),
            ],
            options={
                'verbose_name': '应用场景',
                'verbose_name_plural': '应用场景',
                'db_table': 'product_use_case',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('status', models.PositiveSmallIntegerField(choices=common.enums.PublishStatus.choices, db_index=True, default=common.enums.PublishStatus['DRAFT'], help_text='内容发布状态。', verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, help_text='正式发布时间。', null=True, verbose_name='发布时间')),
                ('name', models.CharField(max_length=160, verbose_name='变体名称')),
                ('code', models.CharField(max_length=120, verbose_name='变体编码')),
                ('voltage', models.CharField(blank=True, max_length=80, verbose_name='电压')),
                ('market', models.CharField(blank=True, max_length=120, verbose_name='市场')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
            ],
            options={
                'verbose_name': '产品变体',
                'verbose_name_plural': '产品变体',
                'db_table': 'product_variant',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=common.enums.PublishStatus.choices, db_index=True, default=common.enums.PublishStatus['DRAFT'], help_text='内容发布状态。', verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, help_text='正式发布时间。', null=True, verbose_name='发布时间')),
                ('slug', models.SlugField(help_text='URL 友好标识。', max_length=160, verbose_name='Slug')),
                ('url_path', models.CharField(help_text='前端 canonical 路径。', max_length=255, verbose_name='URL Path')),
                ('h1', models.CharField(help_text='页面主标题。', max_length=255, verbose_name='H1')),
                ('seo_title', models.CharField(help_text='页面 title。', max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.CharField(help_text='页面 meta description。', max_length=320, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, help_text='可选 canonical 绝对地址。', verbose_name='Canonical URL')),
                ('index_mode', models.PositiveSmallIntegerField(choices=common.enums.IndexMode.choices, db_index=True, default=common.enums.IndexMode['INDEX'], help_text='Index 或 noindex。', verbose_name='索引模式')),
                ('lead_text', models.TextField(blank=True, help_text='页面首段导语。', verbose_name='导语')),
                ('primary_query', models.CharField(blank=True, help_text='核心目标查询。', max_length=160, verbose_name='主查询词')),
                ('secondary_queries', models.TextField(blank=True, help_text='每行一个次级查询词。', verbose_name='次级查询词')),
                ('name', models.CharField(max_length=255, verbose_name='分类名称')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('buyer_fit', models.TextField(blank=True, verbose_name='适合谁')),
                ('selection_guide', models.TextField(blank=True, verbose_name='选型建议')),
                ('is_core_category', models.BooleanField(db_index=True, default=False, verbose_name='是否核心分类')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='L2 子分类填写父分类；L1 顶级分类留空。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='catalog.productcategory', verbose_name='父分类')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'db_table': 'product_category',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('status', models.PositiveSmallIntegerField(choices=common.enums.PublishStatus.choices, db_index=True, default=common.enums.PublishStatus['DRAFT'], help_text='内容发布状态。', verbose_name='发布状态')),
                ('published_at', models.DateTimeField(blank=True, help_text='正式发布时间。', null=True, verbose_name='发布时间')),
                ('slug', models.SlugField(help_text='URL 友好标识。', max_length=160, verbose_name='Slug')),
                ('url_path', models.CharField(help_text='前端 canonical 路径。', max_length=255, verbose_name='URL Path')),
                ('h1', models.CharField(help_text='页面主标题。', max_length=255, verbose_name='H1')),
                ('seo_title', models.CharField(help_text='页面 title。', max_length=255, verbose_name='SEO Title')),
                ('meta_description', models.CharField(help_text='页面 meta description。', max_length=320, verbose_name='Meta Description')),
                ('canonical_url', models.URLField(blank=True, help_text='可选 canonical 绝对地址。', verbose_name='Canonical URL')),
                ('index_mode', models.PositiveSmallIntegerField(choices=common.enums.IndexMode.choices, db_index=True, default=common.enums.IndexMode['INDEX'], help_text='Index 或 noindex。', verbose_name='索引模式')),
                ('lead_text', models.TextField(blank=True, help_text='页面首段导语。', verbose_name='导语')),
                ('primary_query', models.CharField(blank=True, help_text='核心目标查询。', max_length=160, verbose_name='主查询词')),
                ('secondary_queries', models.TextField(blank=True, help_text='每行一个次级查询词。', verbose_name='次级查询词')),
                ('name', models.CharField(max_length=255, verbose_name='产品名称')),
                ('model_code', models.CharField(blank=True, max_length=120, verbose_name='型号')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('buyer_fit', models.TextField(blank=True, verbose_name='适合谁')),
                ('application_summary', models.TextField(blank=True, verbose_name='应用概述')),
                ('buyer_checklist', models.TextField(blank=True, verbose_name='买家检查项')),
                ('customization_support', models.TextField(blank=True, verbose_name='定制支持')),
                ('packing_shipping', models.TextField(blank=True, verbose_name='包装运输')),
                ('after_sales_support', models.TextField(blank=True, verbose_name='售后支持')),
                ('source_url', models.URLField(blank=True, help_text='Bossgoo 原始产品页链接，仅供数据追溯，不对外展示。', max_length=500, verbose_name='来源 URL')),
                ('raw_description', models.TextField(blank=True, help_text='从 Bossgoo 导入的原始产品描述文本，编辑精选后可忽略此字段。', verbose_name='原始描述')),
                ('raw_attributes', models.JSONField(blank=True, default=dict, help_text='从 Bossgoo 导入的原始键值属性（对应 Excel B 区 333 个字段中非空的部分）。此字段为数据存档层，前端展示请使用 ProductSpecGroup/Row。', verbose_name='原始属性')),
                ('is_canonical', models.BooleanField(db_index=True, default=True, verbose_name='是否 canonical')),
                ('category', models.ForeignKey(db_constraint=False, help_text='产品所属分类。', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productcategory', verbose_name='产品分类')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'db_table': 'product',
                'ordering': ('category__name', 'name'),
            },
        ),
    ]
