# Generated by Django 6.0.3 on 2026-03-31 13:31

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('content', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdownload',
            name='asset',
            field=models.ForeignKey(db_constraint=False, help_text='关联的下载文件。', on_delete=django.db.models.deletion.PROTECT, related_name='product_downloads', to='core.mediaasset', verbose_name='下载资源'),
        ),
        migrations.AddField(
            model_name='productdownload',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='所属产品。', on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='所属产品。', on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='asset',
            field=models.ForeignKey(db_constraint=False, help_text='关联的媒体资源。', on_delete=django.db.models.deletion.PROTECT, related_name='product_media_items', to='core.mediaasset', verbose_name='媒体资源'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='所属产品。', on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='关系的源产品。', on_delete=django.db.models.deletion.CASCADE, related_name='product_relations', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='related_product',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='当关系类型为 related_product 时使用。允许关联产品下线后保留当前关系记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_product_relations', to='catalog.product', verbose_name='关联产品'),
        ),
        migrations.AddField(
            model_name='productrelation',
            name='related_resource',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='当关系类型为 related_resource 时使用。允许关联资源下线后保留当前关系记录。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_product_relations', to='content.resourcearticle', verbose_name='关联资源'),
        ),
        migrations.AddField(
            model_name='productspecgroup',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='所属产品。', on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productspecrow',
            name='group',
            field=models.ForeignKey(db_constraint=False, help_text='所属规格组。', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalog.productspecgroup', verbose_name='规格组'),
        ),
        migrations.AddField(
            model_name='productusecase',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='所属产品。', on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(db_constraint=False, help_text='所属产品。', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='产品'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('slug',), name='uniq_product_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('url_path',), name='uniq_product_category_path'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_product_slug_per_category'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('url_path',), name='uniq_product_path'),
        ),
        migrations.AddConstraint(
            model_name='productrelation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('relation_type', apps.catalog.models.ProductRelationType['RELATED_PRODUCT']), ('related_product__isnull', False), ('related_resource__isnull', True)), models.Q(('relation_type', apps.catalog.models.ProductRelationType['RELATED_RESOURCE']), ('related_product__isnull', True), ('related_resource__isnull', False)), _connector='OR'), name='product_relation_matches_target'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'code'), name='uniq_product_variant_code'),
        ),
    ]
