# Generated by Django 6.0.3 on 2026-04-07 04:55

import apps.catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='series',
            field=models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductSeries.choices, db_index=True, default=apps.catalog.models.ProductSeries['COUNTERTOP'], help_text='用于产品列表和相关推荐卡片的货架标签。', verbose_name='产品系列'),
        ),
        migrations.AlterField(
            model_name='product',
            name='after_sales_support',
            field=models.TextField(blank=True, help_text='用于“售后支持”模块，说明保修、备件、远程支持与服务响应。', verbose_name='售后支持'),
        ),
        migrations.AlterField(
            model_name='product',
            name='application_summary',
            field=models.TextField(blank=True, help_text='用于“应用概述 / Applications”模块，解释适用场景、运营环境与典型使用方式；不是 Hero 导语。', verbose_name='应用概述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer_checklist',
            field=models.TextField(blank=True, help_text='用于“买家检查项 / Before you request a quote”模块。建议每行一个检查项，前端按列表展示。', verbose_name='买家检查项'),
        ),
        migrations.AlterField(
            model_name='product',
            name='buyer_fit',
            field=models.TextField(blank=True, help_text='用于“适合谁 / Best fit for”模块。建议每行一个买家类型、门店类型或采购场景。', verbose_name='适合谁'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customization_support',
            field=models.TextField(blank=True, help_text='用于“定制支持”模块，说明 OEM/ODM、品牌、配置定制能力。', verbose_name='定制支持'),
        ),
        migrations.AlterField(
            model_name='product',
            name='lead_text',
            field=models.TextField(blank=True, help_text='用于页面 Hero 标题下的首段导语。应先说明内容适合谁、解决什么问题；不要与摘要重复。', verbose_name='导语'),
        ),
        migrations.AlterField(
            model_name='product',
            name='packing_shipping',
            field=models.TextField(blank=True, help_text='用于“包装运输”模块，说明包装方式、交期、运输与出口安排。', verbose_name='包装运输'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_query',
            field=models.CharField(blank=True, help_text='SEO/GEO 用的核心目标查询词，不在前台直接展示，用于校准 H1、title、meta 与正文主题。', max_length=160, verbose_name='主查询词'),
        ),
        migrations.AlterField(
            model_name='product',
            name='raw_description',
            field=models.TextField(blank=True, help_text='从 Bossgoo 导入的原始描述，仅用于追溯与编辑参考，不在前台直接展示。', verbose_name='原始描述'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_queries',
            field=models.TextField(blank=True, help_text='SEO/GEO 用的次级查询词，每行一个；不在前台直接展示，用于 FAQ、内链、相关资源与内容覆盖规划。', verbose_name='次级查询词'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(blank=True, help_text='用于产品列表卡、相关推荐卡等摘要展示；不要写成产品详情页 Hero 首段导语。建议 1-2 句。', verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='lead_text',
            field=models.TextField(blank=True, help_text='用于页面 Hero 标题下的首段导语。应先说明内容适合谁、解决什么问题；不要与摘要重复。', verbose_name='导语'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='primary_query',
            field=models.CharField(blank=True, help_text='SEO/GEO 用的核心目标查询词，不在前台直接展示，用于校准 H1、title、meta 与正文主题。', max_length=160, verbose_name='主查询词'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='secondary_queries',
            field=models.TextField(blank=True, help_text='SEO/GEO 用的次级查询词，每行一个；不在前台直接展示，用于 FAQ、内链、相关资源与内容覆盖规划。', verbose_name='次级查询词'),
        ),
    ]
