# Generated by Django 6.0.3 on 2026-04-15 07:38

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_series_alter_product_after_sales_support_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='buyer_review_focus_title',
            field=models.CharField(blank=True, help_text='用于分类列表页右侧 Buyer Review Focus 模块标题；为空时前端可回退默认文案。', max_length=120, verbose_name='Buyer Review Focus 标题'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='operational_fit_title',
            field=models.CharField(blank=True, help_text='用于分类列表页左侧 Operational Fit 模块主标题；为空时前端可回退默认文案。', max_length=120, verbose_name='Operational Fit 标题'),
        ),
        migrations.CreateModel(
            name='ProductCategoryOperationalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('section', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductCategoryOperationalSection.choices, db_index=True, help_text='条目属于 Operational Fit 左列，还是 Buyer Review Focus 右列。', verbose_name='所属分组')),
                ('title', models.CharField(help_text='例如 Application Matching、Utility Planning。', max_length=120, verbose_name='标题')),
                ('body', models.TextField(help_text='采购判断说明文案；建议 1-2 句，不要写成空泛营销话术。', verbose_name='正文')),
                ('icon', models.CharField(blank=True, help_text='Material Icon slug，例如 storefront、bolt、fact_check。', max_length=40, verbose_name='图标')),
                ('category', models.ForeignKey(help_text='分类列表页 Operational Fit / Buyer Review Focus 使用的结构化条目。', on_delete=django.db.models.deletion.CASCADE, related_name='operational_items', to='catalog.productcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '分类 Operational Fit 条目',
                'verbose_name_plural': '分类 Operational Fit 条目',
                'db_table': 'product_category_operational_item',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['category', 'section', 'is_active', 'sort_order'], name='idx_cat_oper_item_q')],
                'constraints': [models.UniqueConstraint(fields=('category', 'section', 'sort_order'), name='uniq_cat_oper_item_sort')],
            },
        ),
    ]
