# Generated by Django 6.0.3 on 2026-04-15 13:23

from django.db import migrations, models


TITLE_MAX_LENGTH = 32
BODY_MAX_LENGTH = 120


def trim_operational_item_lengths(apps, schema_editor):
    ProductCategoryOperationalItem = apps.get_model("catalog", "ProductCategoryOperationalItem")

    for item in ProductCategoryOperationalItem.objects.all().only("id", "title", "body"):
        update_fields = []
        if item.title and len(item.title) > TITLE_MAX_LENGTH:
            item.title = item.title[:TITLE_MAX_LENGTH]
            update_fields.append("title")
        if item.body and len(item.body) > BODY_MAX_LENGTH:
            item.body = item.body[:BODY_MAX_LENGTH]
            update_fields.append("body")
        if update_fields:
            item.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productcategory_buyer_review_focus_title_and_more'),
    ]

    operations = [
        migrations.RunPython(trim_operational_item_lengths, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='productcategoryoperationalitem',
            name='body',
            field=models.CharField(help_text='用于两行正文展示；建议 1-2 句，并控制在当前 PLP 两行可承载的英文长度内。', max_length=120, verbose_name='正文'),
        ),
        migrations.AlterField(
            model_name='productcategoryoperationalitem',
            name='title',
            field=models.CharField(help_text='用于单行标题展示；建议控制在当前 PLP 一行可承载的英文长度内。', max_length=32, verbose_name='标题'),
        ),
    ]
