# Generated by Django 6.0.3 on 2026-04-16 10:50

import apps.catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productcategoryoperationalitem_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='sourcing_faq_title',
            field=models.CharField(blank=True, help_text='用于分类列表页 Sourcing FAQ 模块标题；为空时前端可回退默认文案。', max_length=120, verbose_name='Sourcing FAQ 标题'),
        ),
        migrations.CreateModel(
            name='ProductCategoryFaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('placement', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductCategoryFaqPlacement.choices, db_index=True, help_text='FAQ 属于 PLP sourcing FAQ 还是 guide FAQ。', verbose_name='展示位置')),
                ('question', models.CharField(help_text='建议 1 句，直接对应买家会问的问题。', max_length=180, verbose_name='问题')),
                ('answer', models.TextField(help_text='建议 1-3 句，回答要具体、可被搜索和 AI 抽取。', verbose_name='答案')),
                ('category', models.ForeignKey(help_text='分类页 FAQ 条目。', on_delete=django.db.models.deletion.CASCADE, related_name='sourcing_faq_items', to='catalog.productcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '分类 FAQ 条目',
                'verbose_name_plural': '分类 FAQ 条目',
                'db_table': 'product_category_faq_item',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
                'indexes': [models.Index(fields=['category', 'placement', 'is_active', 'sort_order'], name='idx_cat_faq_item_q')],
                'constraints': [models.UniqueConstraint(fields=('category', 'placement', 'sort_order'), name='uniq_cat_faq_item_sort')],
            },
        ),
    ]
