# Generated by Django 6.0.3 on 2026-04-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productcategory_sourcing_faq_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryComparisonOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('title', models.CharField(help_text='Comparison Overview 模块标题。', max_length=160, verbose_name='模块标题')),
                ('intro', models.TextField(blank=True, help_text='Comparison Overview 模块引导语。', verbose_name='模块导语')),
                ('dimension_heading', models.CharField(default='Decision Dimension', help_text='对比矩阵第一列表头。', max_length=80, verbose_name='维度列表头')),
                ('subjects_json', models.JSONField(blank=True, default=list, help_text='数组结构，至少包含 subject_key、label、route_category_slug、sort_order。', verbose_name='对比列定义')),
                ('category', models.OneToOneField(help_text='分类列表页 Comparison Overview 的模块级配置。', on_delete=django.db.models.deletion.CASCADE, related_name='comparison_overview', to='catalog.productcategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '分类 Comparison Overview',
                'verbose_name_plural': '分类 Comparison Overview',
                'db_table': 'product_category_comparison_overview',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryComparisonRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('row_key', models.CharField(help_text='稳定的业务 key，例如 best_fit_service_format。', max_length=80, verbose_name='行标识')),
                ('label', models.CharField(help_text='对比矩阵左侧行标题。', max_length=120, verbose_name='行标题')),
                ('cells_json', models.JSONField(blank=True, default=dict, help_text='以 subject_key 为 key、文案为 value 的映射。', verbose_name='对比单元格')),
                ('overview', models.ForeignKey(help_text='Comparison Overview 下的单行对比维度。', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='catalog.productcategorycomparisonoverview', verbose_name='所属 Comparison Overview')),
            ],
            options={
                'verbose_name': '分类 Comparison Overview 行',
                'verbose_name_plural': '分类 Comparison Overview 行',
                'db_table': 'product_category_comparison_row',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='productcategorycomparisonoverview',
            index=models.Index(fields=['is_active'], name='idx_cat_cmp_overview_active'),
        ),
        migrations.AddIndex(
            model_name='productcategorycomparisonrow',
            index=models.Index(fields=['overview', 'is_active', 'sort_order'], name='idx_cat_cmp_row_q'),
        ),
        migrations.AddConstraint(
            model_name='productcategorycomparisonrow',
            constraint=models.UniqueConstraint(fields=('overview', 'row_key'), name='uniq_cat_cmp_row_key'),
        ),
        migrations.AddConstraint(
            model_name='productcategorycomparisonrow',
            constraint=models.UniqueConstraint(fields=('overview', 'sort_order'), name='uniq_cat_cmp_row_sort'),
        ),
    ]
