# Generated by Django 6.0.3 on 2026-04-20 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_productcategorycomparisonoverview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategorycomparisonoverview",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="Comparison Overview 模块引导语。建议 1-2 句，并控制在 220 个字符以内，避免压坏页面布局。",
                validators=[django.core.validators.MaxLengthValidator(220)],
                verbose_name="模块导语",
            ),
        ),
    ]
