# Generated by Django 6.0.3 on 2026-04-30 00:20

import apps.catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_productcategorycomparisonoverview_intro'),
        ('content', '0003_alter_companypage_lead_text_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategoryGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('hero_eyebrow', models.CharField(blank=True, help_text='Hero 顶部小标题，例如 Editorial Buying Guide。', max_length=80, verbose_name='Hero Eyebrow')),
                ('hero_title', models.CharField(blank=True, help_text='Guide 页主标题；为空时前端可按分类名生成默认标题。', max_length=180, verbose_name='Hero 标题')),
                ('answer_summary', models.TextField(blank=True, help_text='Hero 主摘要。建议 2-4 句，并控制在 420 个字符以内。', validators=[django.core.validators.MaxLengthValidator(420)], verbose_name='Answer Summary')),
                ('hero_primary_cta_label', models.CharField(blank=True, help_text='为空时前端可回退到默认 listing CTA。', max_length=80, verbose_name='Hero 主 CTA 文案')),
                ('hero_primary_cta_href', models.CharField(blank=True, help_text='可留空；为空时前端可回退到当前分类列表页。', max_length=255, verbose_name='Hero 主 CTA 链接')),
                ('hero_secondary_cta_label', models.CharField(blank=True, help_text='为空时前端可回退到默认 inquiry CTA。', max_length=80, verbose_name='Hero 次 CTA 文案')),
                ('hero_secondary_cta_href', models.CharField(blank=True, help_text='可留空；为空时前端可回退到联系或询盘页。', max_length=255, verbose_name='Hero 次 CTA 链接')),
                ('hero_image_alt', models.CharField(blank=True, help_text='Hero 配图 alt 文案。', max_length=160, verbose_name='Hero 图片 Alt')),
                ('hero_note_title', models.CharField(blank=True, help_text='Hero 图旁说明卡标题。', max_length=80, verbose_name='Hero Note 标题')),
                ('hero_note_copy', models.TextField(blank=True, help_text='Hero 图旁说明卡导语。建议控制在 220 个字符以内。', validators=[django.core.validators.MaxLengthValidator(220)], verbose_name='Hero Note 文案')),
                ('hero_note_quote', models.CharField(blank=True, help_text='Hero 引语句子。', max_length=220, verbose_name='Hero 引语')),
                ('hero_note_attribution', models.CharField(blank=True, help_text='Hero 引语来源或署名。', max_length=120, verbose_name='Hero 引语署名')),
                ('definition_title', models.CharField(blank=True, help_text='Definition + Cards 模块标题。', max_length=120, verbose_name='Definition 标题')),
                ('definition_copy', models.TextField(blank=True, help_text='Definition 左侧主文案。建议 2-4 段短句，总长度控制在 700 个字符以内。', validators=[django.core.validators.MaxLengthValidator(700)], verbose_name='Definition 文案')),
                ('contexts_title', models.CharField(blank=True, help_text='Operational Contexts 模块标题。', max_length=120, verbose_name='Operational Contexts 标题')),
                ('matrix_title', models.CharField(blank=True, help_text='Matrix 模块标题。', max_length=120, verbose_name='Matrix 标题')),
                ('matrix_eyebrow', models.CharField(blank=True, help_text='Matrix 模块辅助小标题。', max_length=120, verbose_name='Matrix Eyebrow')),
                ('paths_title', models.CharField(blank=True, help_text='Paths 模块标题。', max_length=120, verbose_name='Paths 标题')),
                ('paths_eyebrow', models.CharField(blank=True, help_text='Paths 模块辅助小标题。', max_length=120, verbose_name='Paths Eyebrow')),
                ('paths_mode', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductCategoryGuidePathMode.choices, default=apps.catalog.models.ProductCategoryGuidePathMode['ROUTE_GUIDANCE'], help_text='只允许 route_guidance 或 next_step_guidance 二选一。', verbose_name='Paths 模式')),
                ('trust_title', models.CharField(blank=True, help_text='Trust/Standards 模块标题。', max_length=120, verbose_name='Standards / Trust 标题')),
                ('trust_copy', models.TextField(blank=True, help_text='Trust/Standards 模块导语。建议控制在 280 个字符以内。', validators=[django.core.validators.MaxLengthValidator(280)], verbose_name='Standards / Trust 文案')),
                ('trust_mode', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductCategoryGuideTrustMode.choices, default=apps.catalog.models.ProductCategoryGuideTrustMode['SHARED_SITEWIDE'], help_text='shared_sitewide、category_curated、hidden 三选一。', verbose_name='Standards / Trust 模式')),
                ('faq_title', models.CharField(blank=True, help_text='Guide FAQ 模块标题；FAQ 条目本身仍复用 ProductCategoryFaqItem。', max_length=120, verbose_name='Guide FAQ 标题')),
                ('resources_title', models.CharField(blank=True, help_text='Related Resources 模块标题。', max_length=120, verbose_name='Related Resources 标题')),
                ('resources_mode', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductCategoryGuideResourcesMode.choices, default=apps.catalog.models.ProductCategoryGuideResourcesMode['SHARED_DEFAULT'], help_text='shared_default、category_curated、hidden 三选一。', verbose_name='Related Resources 模式')),
                ('cta_title', models.CharField(blank=True, help_text='Final CTA 标题。', max_length=160, verbose_name='Final CTA 标题')),
                ('cta_copy', models.TextField(blank=True, help_text='Final CTA 主文案。建议控制在 260 个字符以内。', validators=[django.core.validators.MaxLengthValidator(260)], verbose_name='Final CTA 文案')),
                ('cta_mode', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductCategoryGuideCtaMode.choices, default=apps.catalog.models.ProductCategoryGuideCtaMode['LISTING_FIRST'], help_text='listing_first 或 inquiry_first。', verbose_name='Final CTA 模式')),
                ('cta_primary_label', models.CharField(blank=True, help_text='为空时前端可按 cta_mode 回退默认文案。', max_length=80, verbose_name='Final CTA 主按钮文案')),
                ('cta_primary_href', models.CharField(blank=True, help_text='可留空；为空时前端可按 cta_mode 回退默认链接。', max_length=255, verbose_name='Final CTA 主按钮链接')),
                ('cta_secondary_label', models.CharField(blank=True, help_text='为空时前端可按 cta_mode 回退默认文案。', max_length=80, verbose_name='Final CTA 次按钮文案')),
                ('cta_secondary_href', models.CharField(blank=True, help_text='可留空；为空时前端可按 cta_mode 回退默认链接。', max_length=255, verbose_name='Final CTA 次按钮链接')),
                ('category', models.OneToOneField(help_text='分类 guide 页的模块级配置。', on_delete=django.db.models.deletion.CASCADE, related_name='guide', to='catalog.productcategory', verbose_name='所属分类')),
                ('hero_image', models.ForeignKey(blank=True, db_constraint=False, help_text='Guide Hero 区主图。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_guide_hero_images', to='core.mediaasset', verbose_name='Hero 配图')),
            ],
            options={
                'verbose_name': '分类 Guide',
                'verbose_name_plural': '分类 Guide',
                'db_table': 'product_category_guide',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryGuideItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='记录创建时间。', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='记录最后更新时间。', verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='排序值，越小越靠前。', verbose_name='排序值')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='是否启用。关闭后通常表示不在前台展示，但保留历史数据。', verbose_name='是否启用')),
                ('section', models.PositiveSmallIntegerField(choices=apps.catalog.models.ProductCategoryGuideItemSection.choices, db_index=True, help_text='条目属于 definition_card、operational_context、decision_factor、path、trust_metric、related_resource 中的哪一组。', verbose_name='所属模块')),
                ('item_key', models.CharField(help_text='稳定业务 key，例如 best_for、not_for、cold_vs_dual_temp、entry_compact。', max_length=80, verbose_name='条目标识')),
                ('eyebrow', models.CharField(blank=True, help_text='可选；用于 resource label 或卡片辅助小标题。', max_length=80, verbose_name='Eyebrow')),
                ('title', models.CharField(help_text='条目主标题。', max_length=160, verbose_name='标题')),
                ('body', models.TextField(blank=True, help_text='条目正文；建议控制在 420 个字符以内。', validators=[django.core.validators.MaxLengthValidator(420)], verbose_name='正文')),
                ('supporting_points', models.TextField(blank=True, help_text='多行文本，每行一个 bullet；主要用于 Paths 模块。', validators=[django.core.validators.MaxLengthValidator(420)], verbose_name='补充要点')),
                ('icon', models.CharField(blank=True, help_text='Material Icon slug，例如 storefront、tune、checklist。', max_length=40, verbose_name='图标')),
                ('asset_alt', models.CharField(blank=True, help_text='配图 alt 文案。', max_length=160, verbose_name='图片 Alt')),
                ('href', models.CharField(blank=True, help_text='可填写外链或兜底 href；优先级低于 target_category / target_resource。', max_length=255, verbose_name='兜底链接')),
                ('cta_label', models.CharField(blank=True, help_text='当某些卡片需要显式 CTA 标签时使用。', max_length=80, verbose_name='按钮文案')),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, help_text='Operational Contexts 等图文卡片可使用的配图。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_guide_items', to='core.mediaasset', verbose_name='配图')),
                ('guide', models.ForeignKey(help_text='分类 guide 页下的结构化条目。', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.productcategoryguide', verbose_name='所属 Guide')),
                ('target_category', models.ForeignKey(blank=True, db_constraint=False, help_text='用于 path 或 resource 卡片跳转到某个分类页。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_guide_items', to='catalog.productcategory', verbose_name='目标分类')),
                ('target_resource', models.ForeignKey(blank=True, db_constraint=False, help_text='用于 related resources 卡片跳转到资源文章。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_category_guide_items', to='content.resourcearticle', verbose_name='目标资源')),
            ],
            options={
                'verbose_name': '分类 Guide 条目',
                'verbose_name_plural': '分类 Guide 条目',
                'db_table': 'product_category_guide_item',
                'ordering': ('sort_order', 'id'),
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='productcategoryguide',
            index=models.Index(fields=['is_active'], name='idx_cat_guide_active'),
        ),
        migrations.AddIndex(
            model_name='productcategoryguideitem',
            index=models.Index(fields=['guide', 'section', 'is_active', 'sort_order'], name='idx_cat_guide_item_q'),
        ),
        migrations.AddConstraint(
            model_name='productcategoryguideitem',
            constraint=models.UniqueConstraint(fields=('guide', 'section', 'sort_order'), name='uniq_cat_guide_item_sort'),
        ),
        migrations.AddConstraint(
            model_name='productcategoryguideitem',
            constraint=models.UniqueConstraint(fields=('guide', 'section', 'item_key'), name='uniq_cat_guide_item_key'),
        ),
    ]
